#!/usr/bin/env bash

#SBATCH --partition=pibu_el8
#SBATCH --job-name=meryl
#SBATCH --time=1-00:00:00
#SBATCH --mem=64G
#SBATCH --cpus-per-task=16
#SBATCH --output=/data/users/amaalouf/transcriptome_assembly/output_error/output_meryl_%j.o
#SBATCH --error=/data/users/amaalouf/transcriptome_assembly/output_error/error_meryl_%j.e

# load modules


# set variables
WORK_DIR=/data/users/amaalouf/transcriptome_assembly
RAW_DATA=/data/users/amaalouf/transcriptome_assembly/read_QC/fastp/trimmed/Lu-1/Lu-1_trimmed.fastq.gz
ASSEMBLY_HIFIASM=/data/users/amaalouf/transcriptome_assembly/assemblies/hifiasm_assembly/hifiasm_output.fa
ASSEMBLY_LJA=/data/users/amaalouf/transcriptome_assembly/assemblies/lja_assembly/assembly.fasta
ASSEMBLY_FLYE=/data/users/amaalouf/transcriptome_assembly/assemblies/flye_assembly/assembly.fasta
OUT_DIR=/data/users/amaalouf/transcriptome_assembly/assemblies/assemblies_evaluation/merqury
CONTAINER_SIF_MERQURY=/containers/apptainer/merqury_1.3.sif
CONTAINER_SIF_MERYL=/containers/apptainer/meryl_1.4.1.sif

# create directory if not available
mkdir -p $OUT_DIR $OUT_DIR/hifiasm $OUT_DIR/flye $OUT_DIR/lja $OUT_DIR/hifiasm/merq_out $OUT_DIR/flye/merq_out $OUT_DIR/lja/merq_out

# add MERQURY as a path variable in the script
export MERQURY="/usr/local/share/merqury"

# prepare meryl dbs
# get the right k size
# how i solved this:
#apptainer exec\
# --bind /data/users/amaalouf/transcriptome_assembly\
#  /containers/apptainer/merqury_1.3.sif\
#  sh $MERQURY/best_k.sh 140000000 
# output: tolerable collision rate: 0.001 \\ 18.5126
# so will pick k=19 for the rest
k=19

# build k-mer dbs with meryl
# count: count the occurrences of canonical kmers in the input.  must have 'output' specified
# k=<K>: create mers of size K bases (mandatory)
# output O: write kmers generated by the present command to an output meryl database. O mandatory for count operations.
apptainer exec\
 --bind $WORK_DIR\
  $CONTAINER_SIF_MERYL\
  meryl count k=$k $RAW_DATA output $OUT_DIR/merylout.meryl

# run merqury
# Usage: merqury.sh <read-db.meryl> <asm1.fasta> <out>
#        <read-db.meryl> : k-mer counts of the read set
#        <asm1.fasta>    : Assembly fasta file (ex. pri.fasta, hap1.fasta or maternal.fasta)
#        <out>           : Output prefix
cd $OUT_DIR/hifiasm/merq_out
apptainer exec\
 --bind $WORK_DIR\
  $CONTAINER_SIF_MERQURY\
  merqury.sh $OUT_DIR/merylout.meryl $ASSEMBLY_HIFIASM hifiasm


cd $OUT_DIR/flye/merq_out
apptainer exec\
 --bind $WORK_DIR\
  $CONTAINER_SIF_MERQURY\
  merqury.sh $OUT_DIR/merylout.meryl $ASSEMBLY_FLYE flye


cd $OUT_DIR/lja/merq_out
apptainer exec\
 --bind $WORK_DIR\
  $CONTAINER_SIF_MERQURY\
  merqury.sh $OUT_DIR/merylout.meryl $ASSEMBLY_LJA lja  